spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1154228715

logging:
  level:
    com.tiankong.mapper: info
    org.mybatis: DEBUG
    org.springframework:
        jdbc: DEBUG
        transaction: TRACE
